### ISSUE TITLE
Problema de visulización del home

### ISSUE THREAD

**Issue by damian-garrido** [ciudadanointeligente/del-dicho-al-hecho-ember#74]
Hola @daquiroz @lissteilor @jbci 
hay un problema en la visualización de la portada, se ve así

![image](https://user-images.githubusercontent.com/25389333/76425360-41de2100-6388-11ea-8e4e-c8e087642121.png)

si al archivo /app/templates/components/resumen-study.hbs en la linea 2 le agregas un class="container" quedaría así

![image](https://user-images.githubusercontent.com/25389333/76425485-76ea7380-6388-11ea-9b99-2a0cc1156ed7.png)

salud!

**Comment by daquiroz** [comment]
mil gracias! <3 lo vemos
